---
abstract: 'YAML-based Personal Time Tracking App'
author:
  - 'Ingy döt Net <ingy@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '6.30'
  File::ShareDir::Install: '0.06'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: YamlTime
no_index:
  directory:
    - inc
    - t
    - xt
    - example
requires:
  App::Cmd::Setup: '0'
  Capture::Tiny: '0.11'
  DateTime: '0.70'
  DateTime::Format::Natural: '0.96'
  File::ShareDir: '1.03'
  IO::All: '0.43'
  Module::Pluggable: '0'
  Mouse: '0.93'
  MouseX::App::Cmd: '0.08'
  Template::Plugin::YAMLVal: '0.10'
  Template::Toolkit::Simple: '0.13'
  Term::ReadLine: '1.07'
  Term::ReadLine::Gnu: '1.20'
  Text::CSV_XS: '0.82'
  Text::ParseWords: '3.27'
  YAML::XS: '0.35'
  perl: v5.8.1
resources:
  bugtracker: https://github.com/ingydotnet/yamltime-pm/issues
  homepage: https://github.com/ingydotnet/yamltime-pm
  repository: https://github.com/ingydotnet/yamltime-pm.git
version: '0.12'
